= BSA Store

== Overview

Berisi deskripsi, etimologi penamaan, dan fungsi sistem yang dijabarkan secara singkat. Sekaligus memuat informasi tentang tujuan pengembangan sistem.

== Team Involved

Berikut adalah nama-nama yang terlibat dalam pengembangan sistem BSA Store. Masing-masing sudah dilengkapi dengan alamat email yang dapat dihubungi jika diperlukan.

[cols="30%,35%,35%",frame=all, grid=all]
|===
^.^h| *Name* 
^.^h| *Role* 
^.^h| *Email* 

| I Ketut Agus Yudianto 
| Engineering Manager 
| agusyudi@bsa.id

| Hardiyusa 
| Software Engineer 
| hardiyusa@bsa.id

| Surya Adiputra 
| Software Engineer 
| suryaadiputra@bsa.id
|===

== Technical Information

Berisi informasi teknis tentang sistem, adapun informasi yang dicantumkan harus menyesuaikan dengan kebutuhan.

<<./url-BSA-Store.adoc#, System URL BSA Store>>

<<./architecture-BSA-Store.adoc#, Architecture BSA Store>>

<<./technology-BSA-Store.adoc#, Technology BSA Store>>

<<./environment-BSA-Store.adoc#, Environment BSA Store>>

<<./database-BSA-Store.adoc#, Database Documentation BSA Store>>

<<./release-deploy-BSA-Store.adoc#, Release and Deployment BSA Store>>

<<./flow-wire-BSA-Store.adoc#, Flow and Wireframe BSA Store>>

== Onboarding Information

<<./dev-onboarding-BSA-Store.adoc#, Developer Onboarding BSA Store>>

<<./development-BSA-Store.adoc#, Development BSA Store>>

<<./naming-convention-BSA-Store.adoc#, Naming Convention BSA Store>>

== Documentation

// Berisi dokumen penunjang untuk penggunaan sistem. Berikut adalah dokumen yang biasa dimasukkan di dalamnya. Anda dapat memasukkan external link (Google Doc, Horven, Swagger, maupun lainnya dalam daftar dokumen berikut:

// User Guide (jika ada, external link)

// Dokumen Integrasi (jika ada, external link)

// Dokumen Maintenance (jika ada, external link)

// Dokumen API (jika ada, external link)

<<./release-note-BSA-Store.adoc#, Release Note BSA Store>>
