= Release and Deployment BSA Store

Berisi informasi tentang release dan step deployment

==  Release Schedule and Step

Tidak ada waktu khusus untuk release. Tergantung permintaan PO.

1. To begin the publishing process, select Build > Archive for Publishing:
2. Archive for Publishing builds the project and bundles it into an archive file. The Archive All menu choice archives all archivable projects in the solution. Both options automatically open the Archive Manager when the build and bundling operations complete:
3. Select Ad-Hoc
4. Sign the APK, select provided keystore ask https://t.me/agussuryaadip[]
5. Save at folder
6. Enter password
7. Done
8. APK shared to Infrastructure Teams to publish to Implementation Teams
9. Add Release Note at release-note-systemname.adoc

== Schedule and Step Deployment

Tidak ada waktu khusus untuk release. Tergantung permintaan PO.

1. To begin the publishing process, select Build > Archive for Publishing:
2. Archive for Publishing builds the project and bundles it into an archive file. The Archive All menu choice archives all archivable projects in the solution. Both options automatically open the Archive Manager when the build and bundling operations complete:
3. Select Ad-Hoc
4. Sign the APK, select provided keystore ask https://t.me/agussuryaadip[]
5. Save at folder
6. Enter password
7. Done
8. APK shared to Infrastructure Teams to publish to Implementation Teams
9. Add Release Note at release-note-systemname.adoc