= Perencanaan Web PDAM Jogja

== Overview

Berisi deskripsi, etimologi penamaan, dan fungsi sistem yang dijabarkan secara singkat. Sekaligus memuat informasi tentang tujuan pengembangan sistem.

== Team Involved

Berikut adalah nama-nama yang terlibat dalam _development_ sistem Perencanaan Web PDAM Jogja. Masing-masing sudah dilengkapi dengan alamat email yang dapat dihubungi jika diperlukan. 


[cols="35%,35%,30%",frame=all, grid=all]
|===
^.^h| *Name* 
^.^h| *Role* 
^.^h| *Email*

| I Ketut Agus Yudianto 
| Engineering Manager 
| agusyudi@bsa.id

| I Gede Krisna Putra Andiana 
|  Software Engineer 
| gedekrisna@bsa.id
|===

== Technical Information

//Berisi informasi teknis tentang sistem, adapun informasi yang dicantumkan harus menyesuaikan dengan kebutuhan.

<<./url-Perencanaan-Web-PDAM-Jogja.adoc#, System URL Perencanaan Web PDAM Jogja>>

<<./architecture-Perencanaan-Web-PDAM-Jogja.adoc#, Architecture Perencanaan Web PDAM Jogja>>

<<./technology-Perencanaan-Web-PDAM-Jogja.adoc#, Technology Perencanaan Web PDAM Jogja>>

<<./environment-Perencanaan-Web-PDAM-Jogja.adoc#, Environment Perencanaan Web PDAM Jogja>>

<<./database-Perencanaan-Web-PDAM-Jogja.adoc#, Database Documentation Perencanaan Web PDAM Jogja>>

<<./release-deploy-Perencanaan-Web-PDAM-Jogja.adoc#, Release and Deployment Perencanaan Web PDAM Jogja>>

<<./flow-wire-Perencanaan-Web-PDAM-Jogja.adoc#, Flow and Wireframe Perencanaan Web PDAM Jogja>>

== Onboarding Information

<<./dev-onboarding-Perencanaan-Web-PDAM-Jogja.adoc#, Developer Onboarding Perencanaan Web PDAM Jogja>>

<<./development-Perencanaan-Web-PDAM-Jogja.adoc#, Development Perencanaan Web PDAM Jogja>>

<<./naming-convention-Perencanaan-Web-PDAM-Jogja.adoc#, Naming Convention Perencanaan Web PDAM Jogja>>

== Documentation

//Berisi dokumen penunjang untuk penggunaan sistem. Berikut adalah dokumen yang biasa dimasukkan di dalamnya. Anda dapat memasukkan external link (Google Doc, Horven, Swagger, maupun lainnya dalam daftar dokumen berikut:

//User Guide (jika ada, external link)

//Dokumen Integrasi (jika ada, external link)

//Dokumen Maintenance (jika ada, external link)

//Dokumen API (jika ada, external link)

<<./release-note-Perencanaan-Web-PDAM-Jogja.adoc#, Release Note Perencanaan Web PDAM Jogja>>
