= Library Transaction SIBS

== Overview

Berisi deskripsi, etimologi penamaan, dan fungsi sistem yang dijabarkan secara singkat. Sekaligus memuat informasi tentang tujuan pengembangan sistem.

== Team Involved

Berikut adalah nama-nama yang terlibat dalam _development_ sistem Library Transaction SIBS. Masing-masing sudah dilengkapi dengan alamat email yang dapat dihubungi jika diperlukan. 


[cols="30%,35%,35%",frame=all, grid=all]
|===
^.^h| *Name* 
^.^h| *Role* 
^.^h| *Email* 

| I Ketut Agus Yudianto 
| Engineering Manager 
| agusyudi@bsa.id

| I Ketut Giri Arsa 
| Software Engineer 
| giriarsa@bsa.id
|===

== Technical Information

Berisi informasi teknis tentang sistem, adapun informasi yang dicantumkan harus menyesuaikan dengan kebutuhan.

<<./url-Library-Transaction-SIBS.adoc#, System URL Library Transaction SIBS>>

<<./architecture-Library-Transaction-SIBS.adoc#, Architecture Library Transaction SIBS>>

<<./technology-Library-Transaction-SIBS.adoc#, Technology Library Transaction SIBS>>

<<./environment-Library-Transaction-SIBS.adoc#, Environment Library Transaction SIBS>>

<<./database-Library-Transaction-SIBS.adoc#, Database Documentation Library Transaction SIBS>>

<<./release-deploy-Library-Transaction-SIBS.adoc#, Release and Deployment Library Transaction SIBS>>

<<./flow-wire-Library-Transaction-SIBS.adoc#, Flow and Wireframe Library Transaction SIBS>>

== Onboarding Information

<<./dev-onboarding-Library-Transaction-SIBS.adoc#, Developer Onboarding Library Transaction SIBS>>

<<./development-Library-Transaction-SIBS.adoc#, Development Library Transaction SIBS>>

<<./naming-convention-Library-Transaction-SIBS.adoc#, Naming Convention Library Transaction SIBS>>

== Documentation

// Berisi dokumen penunjang untuk penggunaan sistem. Berikut adalah dokumen yang biasa dimasukkan di dalamnya. Anda dapat memasukkan external link (Google Doc, Horven, Swagger, maupun lainnya dalam daftar dokumen berikut:

// User Guide (jika ada, external link)

// Dokumen Integrasi (jika ada, external link)

// Dokumen Maintenance (jika ada, external link)

// Dokumen API (jika ada, external link)

<<./release-note-Library-Transaction-SIBS.adoc#, Release Note Library Transaction SIBS>>
