= Hublang Web PDAM Parepare

== Overview

Berisi deskripsi, etimologi penamaan, dan fungsi sistem yang dijabarkan secara singkat. Sekaligus memuat informasi tentang tujuan pengembangan sistem.

== Team Involved

Berikut adalah nama-nama yang terlibat dalam pengembangan sistem Hublang Web PDAM Parepare. Masing-masing sudah dilengkapi dengan alamat email yang dapat dihubungi jika diperlukan. 


[cols="30%,35%,35%",frame=all, grid=all]
|===
^.^h| *Name* 
^.^h| *Role* 
^.^h| *Email* 

| I Ketut Agus Yudianto 
| Engineering Manager 
| agusyudi@bsa.id

| I Gede Krisna Putra Andiana 
|  Software Engineer 
| gedekrisna@bsa.id
|===

== Technical Information

Berisi informasi teknis tentang sistem, adapun informasi yang dicantumkan harus menyesuaikan dengan kebutuhan.

<<./url-Hublang-Web-PDAM-Parepare.adoc#, System URL Hublang Web PDAM Parepare>>

<<./architecture-Hublang-Web-PDAM-Parepare.adoc#, Architecture Hublang Web PDAM Parepare>>

<<./technology-Hublang-Web-PDAM-Parepare.adoc#, Technology Hublang Web PDAM Parepare>>

<<./environment-Hublang-Web-PDAM-Parepare.adoc#, Environment Hublang Web PDAM Parepare>>

<<./database-Hublang-Web-PDAM-Parepare.adoc#, Database Documentation Hublang Web PDAM Parepare>>

<<./release-deploy-Hublang-Web-PDAM-Parepare.adoc#, Release and Deployment Hublang Web PDAM Parepare>>

<<./flow-wire-Hublang-Web-PDAM-Parepare.adoc#, Flow and Wireframe Hublang Web PDAM Parepare>>

== Onboarding Information

<<./dev-onboarding-Hublang-Web-PDAM-Parepare.adoc#, Developer Onboarding Hublang Web PDAM Parepare>>

<<./development-Hublang-Web-PDAM-Parepare.adoc#, Development Hublang Web PDAM Parepare>>

<<./naming-convention-Hublang-Web-PDAM-Parepare.adoc#, Naming Convention Hublang Web PDAM Parepare>>

== Documentation

// Berisi dokumen penunjang untuk penggunaan sistem. Berikut adalah dokumen yang biasa dimasukkan di dalamnya. Anda dapat memasukkan external link (Google Doc, Horven, Swagger, maupun lainnya dalam daftar dokumen berikut:

// User Guide (jika ada, external link)

// Dokumen Integrasi (jika ada, external link)

// Dokumen Maintenance (jika ada, external link)

// Dokumen API (jika ada, external link)

<<./release-note-Hublang-Web-PDAM-Parepare.adoc#, Release Note Hublang Web PDAM Parepare>>
