= Bacameter Mandiri Web

== Overview

Berisi deskripsi, etimologi penamaan, dan fungsi sistem yang dijabarkan secara singkat. Sekaligus memuat informasi tentang tujuan pengembangan sistem.

== Team Involved

Berikut adalah nama-nama yang terlibat dalam _development_ sistem Bacameter Mandiri Web. Masing-masing sudah dilengkapi dengan alamat email yang dapat dihubungi jika diperlukan. 

[cols="30%,35%,35%",frame=all, grid=all]
|===
^.^h| *Name* 
^.^h| *Role* 
^.^h| *Email* 

| I Ketut Agus Yudianto 
| Engineering Manager 
| agusyudi@bsa.id

| Hardiyusa 
| Software Engineer 
| hardiyusa@bsa.id

| I Ketut Giri Arsa 
| Software Engineer 
| giriarsa@bsa.id
|===

== Technical Information

Berisi informasi teknis tentang sistem, adapun informasi yang dicantumkan harus menyesuaikan dengan kebutuhan.

<<./url-Bacameter-Mandiri-Web.adoc#, System URL Bacameter Mandiri Web>>

<<./architecture-Bacameter-Mandiri-Web.adoc#, Architecture Bacameter Mandiri Web>>

<<./technology-Bacameter-Mandiri-Web.adoc#, Technology Bacameter Mandiri Web>>

<<./environment-Bacameter-Mandiri-Web.adoc#, Environment Bacameter Mandiri Web>>

<<./database-Bacameter-Mandiri-Web.adoc#, Database Documentation Bacameter Mandiri Web>>

<<./release-deploy-Bacameter-Mandiri-Web.adoc#, Release and Deployment Bacameter Mandiri Web>>

<<./flow-wire-Bacameter-Mandiri-Web.adoc#, Flow and Wireframe Bacameter Mandiri Web>>

== Onboarding Information

<<./dev-onboarding-Bacameter-Mandiri-Web.adoc#, Developer Onboarding Bacameter Mandiri Web>>

<<./development-Bacameter-Mandiri-Web.adoc#, Development Bacameter Mandiri Web>>

<<./naming-convention-Bacameter-Mandiri-Web.adoc#, Naming Convention Bacameter Mandiri Web>>

== Documentation

// Berisi dokumen penunjang untuk penggunaan sistem. Berikut adalah dokumen yang biasa dimasukkan di dalamnya. Anda dapat memasukkan external link (Google Doc, Horven, Swagger, maupun lainnya dalam daftar dokumen berikut:

// User Guide (jika ada, external link)

// Dokumen Integrasi (jika ada, external link)

// Dokumen Maintenance (jika ada, external link)

// Dokumen API (jika ada, external link)

<<./release-note-Bacameter-Mandiri-Web.adoc#, Release Note Bacameter Mandiri Web>>
