= Bacameter.NET
:keywords: bsa-pdam,bacameter-net,bacameter

== Overview

Bacameter.NET merupakan salah satu _desktop app_ (module) SiPDAMPintar yang di-_revamp_ dari Bacameter.NET versi Delphi dengan beberapa _UI/UX improvement_.

== Team Involved

Berikut adalah orang yang terlibat dalam pengembangan sistem Bacameter.NET. Masing-masing sudah dilengkapi dengan alamat _email_ yang bisa dihubungi jika diperlukan.

Software Development Team

[cols="30%,35%,35%",frame=all, grid=all]
|===
^.^h| *Name* 
^.^h| *Role* 
^.^h| *Email* 

| Aryo Indrasmoro 
| Engineering Manager 
| aryo@alterra.id

| Acep Zulkipli Jabar 
| Development Team Lead 
| azul@alterra.id

| Tofa Suriawan 
| Software Engineer 
| tofa@alterra.id

| Ahmad Alfan 
| Software Engineer 
| alfan@alterra.id

| Muhammad Ariyanto Wijaya 
| Software Engineer 
| ariyanto@alterra.id

| Angga Dwi Apria Rifandi 
| Software Engineer 
| angga@alterra.id
|===

UI/UX Design Team	

[cols="30%,35%,35%",frame=all, grid=all]
|===
^.^h| *Name* 
^.^h| *Role* 
^.^h| *Email* 

| Mahfuzi 
| UI & UX Design 
| mahfuzi@alterra.id	
|===

== Technical Information

Berisi informasi teknis tentang sistem, adapun informasi yang dicantumkan harus menyesuaikan dengan kebutuhan.

<<./architecture-bacameter.adoc#, Architecture Bacameter.NET>>

<<./technology-bacameter.adoc#, Technology Bacameter.NET>>

<<./environment-bacameter.adoc#, Environment Bacameter.NET>>

<<./database-bacameter.adoc#, Database Documentation Bacameter.NET>>

<<./release-deploy-bacameter.adoc#, Release and Deployment Bacameter.NET>>

<<./flow-wire-bacameter.adoc#, Flow and Wireframe Bacameter.NET>>

== Onboarding Information

<<./dev-onboarding-bacameter.adoc#, Developer Onboarding Bacameter.NET>>

<<./development-bacameter.adoc#, Development Bacameter.NET>>

<<./naming-convention-bacameter.adoc#, Naming Convention Bacameter.NET>>

== Documentation

Berisi dokumen penunjang untuk penggunaan sistem, berikut adalah dokumen yang biasa dimasukkan di dalamnya. Anda dapat memasukkan external link (Google Doc, Horven, Swagger, maupun lainnya dalam list dokumen berikut:

<<./release-note-bacameter.adoc#, Release Note Bacameter.NET>>
