= Ether Notification

== Overview

Berisi deskripsi, etimologi penamaan, dan fungsi sistem yang dijabarkan secara singkat. Sekaligus memuat informasi tentang tujuan pengembangan sistem.

== Team Involved

Berikut adalah nama-nama yang terlibat dalam pengembangan sistem Ether Notification. Masing-masing sudah dilengkapi dengan alamat email yang dapat dihubungi jika diperlukan. 

[cols="30%,35%,35%",frame=all, grid=all]
|===
^.^h| *Name* 
^.^h| *Role* 
^.^h| *Email* 

| I Ketut Agus Yudianto 
| Engineering Manager 
| agusyudi@bsa.id

| I Wayan Agus Krisna Apriana 
| Software Engineer 
| apriana@bsa.id

| I Gede Krisna Putra Andiana 
| Software Engineer 
| gedekrisna@bsa.id

| I Ketut Giri Arsa 
| Software Engineer 
| giriarsa@bsa.id

| I Made Agus Surya Adiputra 
| Software Engineer 
| suryaadiputra@bsa.id

| Hardiyusa 
| Software Engineer 
| hardiyusa@bsa.id
|===

== Technical Information

Berisi informasi teknis tentang sistem, adapun informasi yang dicantumkan harus menyesuaikan dengan kebutuhan.

<<./url-Ether-Notification.adoc#, System URL Ether Notification>>

<<./architecture-Ether-Notification.adoc#, Architecture Ether Notification>>

<<./technology-Ether-Notification.adoc#, Technology Ether Notification>>

<<./environment-Ether-Notification.adoc#, Environment Ether Notification>>

<<./database-Ether-Notification.adoc#, Database Documentation Ether Notification>>

<<./release-deploy-Ether-Notification.adoc#, Release and Deployment Ether Notification>>

<<./flow-wire-Ether-Notification.adoc#, Flow and Wireframe Ether Notification>>

== Onboarding Information

<<./dev-onboarding-Ether-Notification.adoc#, Developer Onboarding Ether Notification>>

<<./development-Ether-Notification.adoc#, Development Ether Notification>>

<<./naming-convention-Ether-Notification.adoc#, Naming Convention Ether Notification>>

== Documentation

Berisi dokumen penunjang untuk penggunaan sistem. Berikut adalah dokumen yang biasa dimasukkan di dalamnya. Anda dapat memasukkan external link (Google Doc, Horven, Swagger, maupun lainnya dalam daftar dokumen berikut:

User Guide (jika ada, external link)

Dokumen Integrasi (jika ada, external link)

Dokumen Maintenance (jika ada, external link)

Dokumen API (jika ada, external link)


<<./release-note-Ether-Notification.adoc#, Release Note Ether Notification>>
