name: coba push

on:
  push:
    branches:
      - master

jobs:
 run script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 
      
      - name: execute py script 
        run: python coba.py 
     