= PDAM Info

== Overview

Berisi deskripsi, etimologi penamaan, dan fungsi sistem yang dijabarkan secara singkat. Sekaligus memuat informasi tentang tujuan pengembangan sistem.

== Team Involved

Berikut adalah nama-nama yang terlibat dalam _development_ sistem PDAM Info. Masing-masing sudah dilengkapi dengan alamat email yang dapat dihubungi jika diperlukan. 


[cols="35%,35%,30%",frame=all, grid=all]
|===
^.^h| *Name* 
^.^h| *Role* 
^.^h| *Email*

| I Ketut Agus Yudianto 
| Engineering Manager 
| agusyudi@bsa.id

| Hardiyusa 
| Software Engineer 
| hardiyusa@bsa.id

| I Made Agus Surya Adiputra 
| Software Engineer 
| suryaadiputra@bsa.id
|===

== Technical Information

Berisi informasi teknis tentang sistem, adapun informasi yang dicantumkan harus menyesuaikan dengan kebutuhan.

<<./url-PDAM-Info.adoc#, System URL PDAM Info>>

<<./architecture-PDAM-Info.adoc#, Architecture PDAM Info>>

<<./technology-PDAM-Info.adoc#, Technology PDAM Info>>

<<./environment-PDAM-Info.adoc#, Environment PDAM Info>>

<<./database-PDAM-Info.adoc#, Database Documentation PDAM Info>>

<<./release-deploy-PDAM-Info.adoc#, Release and Deployment PDAM Info>>

<<./flow-wire-PDAM-Info.adoc#, Flow and Wireframe PDAM Info>>

== Onboarding Information

<<./dev-onboarding-PDAM-Info.adoc#, Developer Onboarding PDAM Info>>

<<./development-PDAM-Info.adoc#, Development PDAM Info>>

<<./naming-convention-PDAM-Info.adoc#, Naming Convention PDAM Info>>

== Documentation

//Berisi dokumen penunjang untuk penggunaan sistem. Berikut adalah dokumen yang biasa dimasukkan di dalamnya. Anda dapat memasukkan external link (Google Doc, Horven, Swagger, maupun lainnya dalam daftar dokumen berikut:

//User Guide (jika ada, external link)

//Dokumen Integrasi (jika ada, external link)

//Dokumen Maintenance (jika ada, external link)

//Dokumen API (jika ada, external link)

<<./release-note-PDAM-Info.adoc#, Release Note PDAM Info>>
