= SiPintar BSBS ver 4

== Overview

Berisi deskripsi, etimologi penamaan, dan fungsi sistem yang dijabarkan secara singkat. Sekaligus memuat informasi tentang tujuan pengembangan sistem.



== Team Involved

Berikut adalah nama-nama yang terlibat dalam pengembangan sistem SiPintar BSBS ver 4. Masing-masing sudah dilengkapi dengan alamat email yang dapat dihubungi jika diperlukan. 

[cols="35%,35%,30%",frame=all, grid=all]
|===
^.^h| *Name* 
^.^h| *Role* 
^.^h| *Email*

| Tuagus Mardeka 
| Software Engineer 
| dika@bsa.id

| Detut Indra S.A.N 
| Software Engineer 
| detut@bsa.id

| Angga Wira Prayudi 
| Software Engineer 
| prayudi@bsa.id

| Prawira Ariadi 
| Software Engineer 
| wira@bsa.id
|===

== Technical Information

//Berisi informasi teknis tentang sistem, adapun informasi yang dicantumkan harus menyesuaikan dengan kebutuhan.

<<./url-SiPintar-BSBS-ver-4.adoc#, System URL SiPintar BSBS ver 4>>

<<./architecture-SiPintar-BSBS-ver-4.adoc#, Architecture SiPintar BSBS ver 4>>

<<./technology-SiPintar-BSBS-ver-4.adoc#, Technology SiPintar BSBS ver 4>>

<<./environment-SiPintar-BSBS-ver-4.adoc#, Environment SiPintar BSBS ver 4>>

<<./database-SiPintar-BSBS-ver-4.adoc#, Database Documentation SiPintar BSBS ver 4>>

<<./release-deploy-SiPintar-BSBS-ver-4.adoc#, Release and Deployment SiPintar BSBS ver 4>>

<<./flow-wire-SiPintar-BSBS-ver-4.adoc#, Flow and Wireframe SiPintar BSBS ver 4>>

== Onboarding Information

<<./dev-onboarding-SiPintar-BSBS-ver-4.adoc#, Developer Onboarding SiPintar BSBS ver 4>>

<<./development-SiPintar-BSBS-ver-4.adoc#, Development SiPintar BSBS ver 4>>

<<./naming-convention-SiPintar-BSBS-ver-4.adoc#, Naming Convention SiPintar BSBS ver 4>>

== Documentation

//Berisi dokumen penunjang untuk penggunaan sistem. Berikut adalah dokumen yang biasa dimasukkan di dalamnya. Anda dapat memasukkan external link (Google Doc, Horven, Swagger, maupun lainnya dalam daftar dokumen berikut:

//User Guide (jika ada, external link)

//Dokumen Integrasi (jika ada, external link)

//Dokumen Maintenance (jika ada, external link)

//Dokumen API (jika ada, external link)

<<./release-note-SiPintar-BSBS-ver-4.adoc#, Release Note SiPintar BSBS ver 4>>
